site_name: Simulation Workshop
site_url: https://simulation-workshop.github.io/simulation-workshop/

nav:
  - Home: index.md
  - Workshops:
    - Modelica: Workshops/Modelica_Workshop.md
    #- Python: Python_Workshop.md
    #- Julia: Julia_Workshop.md
  - Articles: 
    - What is a model: Articles/What_is_model.md
    - Purpose of a simulation: Articles/Story-telling-simulation.md
    - Models vs Simulations: Articles/Models-vs-simulations.md
  - Quizes: 
      - Modelica Quiz: Quiz/Modelica_Quiz.md
  - About: about.md
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep orange

  font:
    text: Open Sans
    code: Roboto Mono

  
  logo: assets/small_log.png
  favicon: assets/favicon.ico

  features:
    - navigation.footer

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/simulation-workshop
      name: GitHub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vaisakh-t-v-4a3505112/
      name: LinkedIn

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@systemModelingChannel
      name: YouTube

plugins:
  - search
  - mkdocs_quiz
  







